### PR TITLE
Add a note stating that modification on array primitives is supported…

### PR DESCRIPTION
**Pull request by opensas**
… in svelte 3.23.1 onwards

Check #36 for context

https://github.com/svelte-society/recipes-mvp/issues/36

### CODE REVIEW

**Comment by babycourageous** [comment]
I wonder if instead of the disclaimer in the middle of the **each** section we should explicitly state at the beginning something like "that from svelte version 3.23.1 onwards the following issue no longer applies" - similar to language used in https://github.com/svelte-society/recipes-mvp/issues/36 title
 
That way it is 100% clear that the entire section is basically an archived section for older versions of Svelte. 

Should we add the old and new REPL examples or link to official Svelte issue as you did in https://github.com/svelte-society/recipes-mvp/issues/36 ?

Thoughts?

**Comment by swyxio** [comment]
oo @babycourageous good call! i like that attention to detail. want to modify it?

**Comment by babycourageous** [comment]
Sure thing!

**Comment by swyxio** [comment]
awesome, thank you everyone!!

**Comment by opensas** [comment]
Yea, agree with it all, it's more clear and it has way more information.

BTW, I'm not planning to alter those repls, but perhaps it might be a good ideain these cases to have the repls from and oficial svelte account, so we make sure they won't be altered

**Pull request merged**
