### PR TITLE
Authentication method for the README.md

### PR DESCRIPTION
**Pull request by dmgolembiowski**
…ticate using a JSON post API method.

### CODE REVIEW

**Comment by kevmodrome** [comment]
I think it would be a good idea to write some accompanying text to this. What is it that we are doing? Explain to the reader how this works.

**Comment by dmgolembiowski** [comment]
Sounds like a good idea; I'll amend the section to include what authentication is, what it can be used for, and how to achieve it.

**Comment by swyxio** [comment]
we appreciate your contribution anyway :) pls feel free to contrib whatever you can

**Comment by dmgolembiowski** [comment]
@kevmodrome and @sw-yx, is my latest commit to the README more aligned with what you are going for? If not, I have a separate post on [EdgeDB's Spectrum Chat](https://spectrum.chat/edgedb/general/personal-accomplishment-edgedb-authentication-from-svelte-js~ff16a60c-91b2-4e85-aa13-1aa3d22d9500) where I go a little more into detail on the topic. I'm happy to incorporate elements from there if that's more relevant.

**Comment by swyxio** [comment]
LGTM!

**Pull request merged**
